steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/play-parl-ai:${_TAG}', '-f', 'Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/play-parl-ai:${_TAG}', 'gcr.io/$PROJECT_ID//play-parl-ai:latest']
timeout: 900s
substitutions:
  _TAG: '0.1'
images:
- 'gcr.io/$PROJECT_ID/play-parl-ai:latest'
- 'gcr.io/$PROJECT_ID/play-parl-ai:${_TAG}'
